# application.yaml
server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/HuntSphere
    username: HuntSphere
    password: HuntSphere
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    change-log: db/changelog/master.yaml

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/huntsphere
          jwk-set-uri: http://localhost:8080/realms/huntsphere/protocol/openid-connect/certs

keycloak:
  realm: huntsphere
  auth-server-url: http://localhost:8080
  resource: huntsphere-backend
  credentials:
    secret: hD3aNfUcqjMKwJduCBh2e4uzKd6YXrKJ
  bearer-only: true
  public-client: false
  # Add these new lines
  admin:
    client-id: admin-cli
    client-secret: 02RO89kZh884yeb8BTpzZsklJrjvHVhl  # Replace with your actual admin client secret

logging:
  level:
    org.springframework.security: DEBUG
    org.keycloak: DEBUG
    org.banta.huntsphere: DEBUG