server:
  port: 8081

spring:
  mvc:
    throw-exception-if-no-handler-found: true
    jackson:
      serialization:
        WRITE_DATES_AS_TIMESTAMPS: false
      deserialization:
        FAIL_ON_UNKNOWN_PROPERTIES: false
    jpa:
      properties:
        hibernate:
          format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: HuntSphere
    password: HuntSphere
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: db/changelog/master.yaml

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.banta: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG